src/restaurant_web_app/menus/urls.py
from django.conf.urls import url

from menus.views import (
	ItemListView,
	ItemDetailView,
	ItemCreateView,
	ItemUpdateView
)

urlpatterns = [
	url( r'^$', ItemListView.as_view(), name = 'list' ), #class based view
    url( r'^create/$', ItemCreateView.as_view(), name = 'create' ),   
    # url( r'^(?P<pk>[\w-]+)/edit/$', ItemUpdateView.as_view(), name = 'update' ), 
    
    url( r'^(?P<pk>[\w-]+)/$', ItemUpdateView.as_view(), name = 'detail' ),
]

src/restaurant_web_app/restaurant_web_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView
from profiles.views import ProfileFollowToggle

"""
from restaurants.views import (
    restaurant_listview,
    RestaurantListView,
    RestaurantDetailView,
    restaurant_createview,
    RestaurantCreateView
    #SpicesRestaurantListView,
    #AfricanDishRestaurantListView,
    #SearchRestaurantListView,
     #HomeView #, AboutView, ContactView #, ContactTemplateView
)
"""
urlpatterns = [
    url(r'^admin/', admin.site.urls, name = 'admin' ),
    url( r'^login/$', LoginView.as_view(), name = 'login' ),
    url( r'^profile-follow/$', ProfileFollowToggle.as_view(), name = 'follow' ),
    #url( r'^$', home ),
    #url( r'^about$', about ), #function based view
    #url( r'^contact$', contact ),
    #url( r'^contact/(?P<id>\d+)/$', ContactView.as_view() ),
    url( r'^$', TemplateView.as_view( template_name = 'home.html' ), name = 'home' ),
    # url( r'^about/$', AboutView.as_view() ),
    # url( r'^contact/$', ContactView.as_view() ),
    url( r'^about/$', TemplateView.as_view( template_name = 'about.html' ), name = 'about' ),
    url( r'^contact/$', TemplateView.as_view( template_name = 'contact.html' ), name = 'contact' ),
    #url( r'^restaurants/$', restaurant_listview ), #function based view
    #url( r'^restaurants/create/$', restaurant_createview ),
    url( r'u/', include( 'profiles.urls', namespace = 'profiles' ) ),
    url(r'^items/', include('menus.urls', namespace = 'menus' ) ),
    url(r'^restaurants/', include('restaurants.urls', namespace = 'restaurants' ) ),
    #url( r'^restaurants/create/$', RestaurantCreateView.as_view(), name = 'restaurants-create' ),
    #url( r'^restaurants/(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(), name = 'restaurants-detail' )
    #url( r'^restaurants/$', RestaurantListView.as_view(), name = 'restaurants' ), #class based view
    #url( r'^restaurants/(?P<slug>\w+)/$', SearchRestaurantListView.as_view() ),
    #url( r'^restaurants/(?P<slug>\w+)/$', RestaurantListView.as_view() ),
    #url( r'^restaurants/(?P<rest_id>\w+)/$', RestaurantDetailView.as_view() ) # its always id or pk or slug else overwrite it in method to e.g rest_id
    #url( r'^restaurants/spices/$', SpicesRestaurantListView.as_view() ),
    #url( r'^restaurants/african/$', AfricanDishRestaurantListView.as_view() ),
    
]

src/restaurant_web_app/templates/snipets/css.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> 

src/restaurant_web_app/templates/snipets/form-snippet.html
{% if form.errors.none_field_errors %}
{{ form.errors.none_field_errors }}
{% endif %}

<form method = "POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Save</button>
</form>

src/restaurant_web_app/templates/snipets/js.html
 {% load static %}
 <script type="text/javascript" src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
 <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>

src/restaurant_web_app/templates/snipets/nav.html
<div class="nav">
	<a href="{% url 'home' %}">home</a>
	<a href="{% url 'about' %}">about</a>
	<a href="{% url 'contact' %}">contact</a>
	{% if request.user.is_authenticated %}
		<a href="{% url 'restaurants:list' %}">restaurants</a>
		<a href="{% url 'menus:list' %}">Menu Items</a>

	{% endif %}
	<a href="/admin">admin</a>
</div>

src/restaurant_web_app/templates/snipets/sidebar.html
<ul>
	<li>Item 1</li>
	<li>Item 2</li>
	<li>Item 3</li>
</ul>