src/restaurant_web_app/menus/urls.py
from django.conf.urls import url

from menus.views import (
	ItemListView,
	ItemDetailView,
	ItemCreateView,
	ItemUpdateView
)

urlpatterns = [
	url( r'^$', ItemListView.as_view(), name = 'list' ), #class based view
    url( r'^create/$', ItemCreateView.as_view(), name = 'create' ),   
    # url( r'^(?P<pk>[\w-]+)/edit/$', ItemUpdateView.as_view(), name = 'update' ), 
    
    url( r'^(?P<pk>[\w-]+)/$', ItemUpdateView.as_view(), name = 'detail' ),
]

src/restaurant_web_app/restaurant_web_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView
from profiles.views import ProfileFollowToggle

"""
from restaurants.views import (
    restaurant_listview,
    RestaurantListView,
    RestaurantDetailView,
    restaurant_createview,
    RestaurantCreateView
    #SpicesRestaurantListView,
    #AfricanDishRestaurantListView,
    #SearchRestaurantListView,
     #HomeView #, AboutView, ContactView #, ContactTemplateView
)
"""
urlpatterns = [
    url(r'^admin/', admin.site.urls, name = 'admin' ),
    url( r'^login/$', LoginView.as_view(), name = 'login' ),
    url( r'^profile-follow/$', ProfileFollowToggle.as_view(), name = 'follow' ),
    #url( r'^$', home ),
    #url( r'^about$', about ), #function based view
    #url( r'^contact$', contact ),
    #url( r'^contact/(?P<id>\d+)/$', ContactView.as_view() ),
    url( r'^$', TemplateView.as_view( template_name = 'home.html' ), name = 'home' ),
    # url( r'^about/$', AboutView.as_view() ),
    # url( r'^contact/$', ContactView.as_view() ),
    url( r'^about/$', TemplateView.as_view( template_name = 'about.html' ), name = 'about' ),
    url( r'^contact/$', TemplateView.as_view( template_name = 'contact.html' ), name = 'contact' ),
    #url( r'^restaurants/$', restaurant_listview ), #function based view
    #url( r'^restaurants/create/$', restaurant_createview ),
    url( r'u/', include( 'profiles.urls', namespace = 'profiles' ) ),
    url(r'^items/', include('menus.urls', namespace = 'menus' ) ),
    url(r'^restaurants/', include('restaurants.urls', namespace = 'restaurants' ) ),
    #url( r'^restaurants/create/$', RestaurantCreateView.as_view(), name = 'restaurants-create' ),
    #url( r'^restaurants/(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(), name = 'restaurants-detail' )
    #url( r'^restaurants/$', RestaurantListView.as_view(), name = 'restaurants' ), #class based view
    #url( r'^restaurants/(?P<slug>\w+)/$', SearchRestaurantListView.as_view() ),
    #url( r'^restaurants/(?P<slug>\w+)/$', RestaurantListView.as_view() ),
    #url( r'^restaurants/(?P<rest_id>\w+)/$', RestaurantDetailView.as_view() ) # its always id or pk or slug else overwrite it in method to e.g rest_id
    #url( r'^restaurants/spices/$', SpicesRestaurantListView.as_view() ),
    #url( r'^restaurants/african/$', AfricanDishRestaurantListView.as_view() ),
    
]

src/restaurant_web_app/menus/models.py
from django.conf import settings
from django.db import models

from django.core.urlresolvers import reverse
from restaurants.models import RestaurantLocation

# Create your models here.
class Item( models.Model ):
	user = models.ForeignKey( settings.AUTH_USER_MODEL )
	restaurant = models.ForeignKey( RestaurantLocation )
	name = models.CharField( max_length=120 )
	contents = models.TextField( help_text = 'seperate items by comma' )
	excludes = models.TextField( blank = True, null = True, help_text = 'seperate items by comma' )
	public = models.BooleanField( default = True )
	timestamp = models.DateTimeField( auto_now_add = True )
	updated = models.DateTimeField( auto_now = True )

	class Meta:
		ordering = [ '-updated', '-timestamp' ] #Item.objects.all() most recent

	def get_contents( self ):
		return self.contents.split( "," )

	def get_excludes( self ):
		return self.excludes.split( "," )

	def __str__( self ):
		return self.name

	def get_absolute_url( self ):
		return reverse( 'menus:detail', kwargs={'pk' : self.pk } )

src/restaurant_web_app/menus/forms.py
from django import forms

from restaurants.models import RestaurantLocation
from .models import Item

class ItemForm( forms.ModelForm ):
	class Meta:
		model = Item
		fields = [
			'restaurant',
			'name',
			'contents',
			'excludes',
			'public'
		]

	def __init__( self, user=None, *args, **kwargs ):
		#print( kwargs.pop( 'user' ) )
		print( user )
		#print( kwargs.pop( 'instance' ) )
		#print( 'instance' )
		super( ItemForm, self ).__init__( *args, **kwargs )
		self.fields[ 'restaurant' ].queryset = RestaurantLocation.objects.filter( owner = user )#.exclude( item__isnull = False )

src/restaurant_web_app/menus/views.py
#from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .forms import ItemForm
from .models import Item
# Create your views here.


class ItemListView( ListView ):
	def get_queryset( self ):
		return Item.objects.filter( user = self.request.user )

class ItemDetailView( DetailView ):
	def get_queryset( self ):
		return Item.objects.filter( user = self.request.user )

class ItemCreateView( LoginRequiredMixin, CreateView ):
	template_name = 'menus/form.html'
	form_class = ItemForm

	def form_valid( self, form ):
		obj = form.save( commit = False )
		obj.user = self.request.user
		return super( ItemCreateView, self ).form_valid( form )

	def get_form_kwargs( self ):
		kwargs = super( ItemCreateView, self ).get_form_kwargs()
		kwargs[ 'user' ] = self.request.user
		#kwargs[ 'instance' ] = Item.objects.filter( user=self.request.user ).first()
		return kwargs

	def get_queryset( self ):
		return Item.objects.filter( user=self.request.user )

	def get_context_data( self, *args, **kwargs ):
		context = super( ItemCreateView, self ).get_context_data( *args, **kwargs )
		context[ 'title' ] = 'Add Item'
		return context

class ItemUpdateView( LoginRequiredMixin, UpdateView ):
	#template_name = 'menus/form.html'
	template_name = 'menus/detail-update.html'
	form_class = ItemForm
	def get_queryset( self ):
		return Item.objects.filter( user=self.request.user )

	def get_context_data( self, *args, **kwargs ):
		context = super( ItemUpdateView, self ).get_context_data( *args, **kwargs )
		context[ 'title' ] = 'Update Item'
		return context

	def get_form_kwargs( self ):
		kwargs = super( ItemUpdateView, self ).get_form_kwargs()
		kwargs[ 'user' ] = self.request.user
		#kwargs[ 'instance' ] = Item.objects.filter( user=self.request.user ).first()
		return kwargs

src/restaurant_web_app/menus/templates/menus/detail-update.html
detail-update.html{% extends 'base.html' %}

{% block head_title %} Menu Item | {{ block.super }} {% endblock %}

{% block content %}

	<h1>{{ form.instance.name }}</h1>
	<h1>Restaurant location:{{ form.instance.restaurant.name }}</h1>
		{% if form.instance.contents %}
		Contents
		<ul>
			{% for item in form.instance.get_contents %}
			<li>{{ item }}</li>
			{% endfor %}
		</ul>
		{% endif %}

		{% if form.instance.excludes %}
		Excludes
		<ul>
			{% for item in form.instance.get_excludes %}
			<li>{{ item }}</li>
			{% endfor %}
		</ul>
		{% endif %}

	</li>

<hr>
<h3>Make Changes</h3>

{% include 'snipets/form-snippet.html'  with form=form %}

{% endblock %}

src/restaurant_web_app/menus/templates/menus/form.html
{% extends 'base.html' %}

{% block head_title %} {{ title }} | {{ block.super }} {% endblock %}

{% block content %}

<h1>{{ title }}</h1>

{% if form.errors.none_field_errors %}
{{ form.errors.none_field_errors }}
{% endif %}

<form method = "POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Save</button>
</form>

{% if form.instance %}
	<h1>{{ form.instance.name }}</h1>
{% endif %}

{% endblock %}

<!-- <input type="text" name="name" placeholder="Your Title"><br>
<input type="text" name="location" placeholder="Your location"><br>
<input type="text" name="category" placeholder="Your category"><br> -->

src/restaurant_web_app/menus/templates/menus/item_detail.html
{% extends 'base.html' %}

{% block head_title %} Menu Item | {{ block.super }} {% endblock %}

{% block content %}

	<h1>{{ object.name }}</h1>
	<h1>Restaurant location:{{ object.restaurant.name }}</h1>
		{% if object.contents %}
		Contents
		<ul>
			{% for item in object.get_contents %}
			<li>{{ item }}</li>
			{% endfor %}
		</ul>
		{% endif %}

		{% if object.excludes %}
		Excludes
		<ul>
			{% for item in object.get_excludes %}
			<li>{{ item }}</li>
			{% endfor %}
		</ul>
		{% endif %}

	</li>


{% endblock %}

src/restaurant_web_app/menus/templates/menus/item_list.html
{% extends 'base.html' %}

{% block head_title %} Menu Items | {{ block.super }} {% endblock %}

{% block content %}
<h1>Menu Items List <small><a href="{% url 'menus:create' %}">Add</a></small></h1>

<ul>
	{% for obj in object_list %}
	<li><a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a><br>
		{% if obj.contents %}
		Contents
		<ul>
			{% for item in obj.get_contents %}
			<li>{{ item }}</li>
			{% endfor %}
		</ul>
		{% endif %}

		{% if obj.excludes %}
		Excludes
		<ul>
			{% for item in obj.get_excludes %}
			<li>{{ item }}</li>
			{% endfor %}
		</ul>
		{% endif %}
			{% empty %}
			<li> <a href="{% url 'menus:create' %}">Add menu Item</a> </li>
	</li>
	{% endfor %}
</ul>
{% endblock %}